# Generated by Django 3.1 on 2020-08-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('catchPhrase', models.CharField(max_length=30)),
                ('bs', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=30)),
                ('Address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.address')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task1.company')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='id_geo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.geo'),
        ),
    ]
