# Generated by Django 3.1 on 2020-08-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='id_geo',
            new_name='geo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Address_id',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='company_id',
            new_name='company',
        ),
    ]
